CREATE SEQUENCE medicamento_base_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(255),
    sexo VARCHAR(20) NOT NULL,
    logradouro VARCHAR(255),
    numero VARCHAR(50),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(2),
    cep VARCHAR(20),
    plano_saude VARCHAR(255),
    ativo BOOLEAN NOT NULL,
    CONSTRAINT uk_pacientes_cpf UNIQUE (cpf)
);

CREATE TABLE tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority VARCHAR(100) NOT NULL,
    CONSTRAINT uk_tb_role_authority UNIQUE (authority)
);

CREATE TABLE tb_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    logradouro VARCHAR(255),
    numero VARCHAR(50),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(2),
    cep VARCHAR(20),
    ativo BOOLEAN NOT NULL,
    CONSTRAINT uk_tb_usuarios_login UNIQUE (login),
    CONSTRAINT uk_tb_usuarios_email UNIQUE (email),
    CONSTRAINT uk_tb_usuarios_cpf UNIQUE (cpf)
);

CREATE TABLE tb_medicos (
    usuario_id BIGINT PRIMARY KEY,
    crm VARCHAR(50) NOT NULL,
    especialidade VARCHAR(120),
    instituicao_formacao VARCHAR(255),
    data_formacao DATE,
    sexo VARCHAR(20),
    observacoes VARCHAR(1000),
    CONSTRAINT uk_tb_medicos_crm UNIQUE (crm),
    CONSTRAINT fk_tb_medicos_usuario
        FOREIGN KEY (usuario_id) REFERENCES tb_usuarios (id)
);

CREATE TABLE enfermeiros (
    id BIGINT PRIMARY KEY,
    coren VARCHAR(50) NOT NULL,
    uf_coren VARCHAR(2) NOT NULL,
    especialidade_enfermagem VARCHAR(120),
    setor_clinico VARCHAR(50),
    turno_trabalho VARCHAR(30),
    data_admissao DATE,
    data_demissao DATE,
    observacoes VARCHAR(1000),
    CONSTRAINT uk_enfermeiros_coren UNIQUE (coren),
    CONSTRAINT fk_enfermeiros_usuario
        FOREIGN KEY (id) REFERENCES tb_usuarios (id),
    CONSTRAINT ck_enfermeiros_setor_clinico
        CHECK (setor_clinico IS NULL OR setor_clinico IN (
            'AMBULATORIO','EMERGENCIA','UTI','CENTRO_CIRURGICO',
            'ENFERMARIA','PEDIATRIA','GINECOLOGIA','OUTRO'
        )),
    CONSTRAINT ck_enfermeiros_turno_trabalho
        CHECK (turno_trabalho IS NULL OR turno_trabalho IN (
            'MANHA','TARDE','NOITE','INTEGRAL','PLANTAO'
        ))
);

CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    valor_consulta NUMERIC(10,2),
    meio_pagamento VARCHAR(20) NOT NULL,
    pago BOOLEAN NOT NULL,
    data_pagamento TIMESTAMP,
    duracao_minutos INTEGER,
    retorno BOOLEAN NOT NULL,
    data_limite_retorno TIMESTAMP,
    link_acesso VARCHAR(255),
    plano_saude VARCHAR(255),
    numero_carteirinha VARCHAR(255),
    motivo VARCHAR(500),
    anamnese VARCHAR(4000),
    exame_fisico VARCHAR(4000),
    diagnostico VARCHAR(4000),
    prescricao VARCHAR(4000),
    observacoes VARCHAR(2000),
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    CONSTRAINT fk_consultas_paciente
        FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT fk_consultas_medico
        FOREIGN KEY (medico_id) REFERENCES tb_medicos (usuario_id),
    CONSTRAINT ck_consultas_tipo
        CHECK (tipo IN ('PRESENCIAL','TELECONSULTA','RETORNO','URGENCIA')),
    CONSTRAINT ck_consultas_status
        CHECK (status IN ('AGENDADA','CONFIRMADA','EM_ATENDIMENTO','CONCLUIDA','CANCELADA','NAO_COMPARECEU')),
    CONSTRAINT ck_consultas_meio_pagamento
        CHECK (meio_pagamento IN ('DEBITO','CREDITO','PIX','DINHEIRO'))
);

CREATE TABLE exame_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    codigo_tuss VARCHAR(255),
    tipo VARCHAR(30) NOT NULL,
    prazo_estimado INTEGER NOT NULL,
    CONSTRAINT uk_exame_base_codigo_tuss UNIQUE (codigo_tuss),
    CONSTRAINT ck_exame_base_tipo
        CHECK (tipo IN ('LABORATORIAL','IMAGEM','OUTRO'))
);

CREATE TABLE medicamento_base (
    id BIGINT PRIMARY KEY DEFAULT nextval('medicamento_base_seq'),
    nome_comercial VARCHAR(255),
    principio_ativo VARCHAR(255),
    dcb VARCHAR(255),
    forma_farmaceutica VARCHAR(120),
    dosagem_padrao VARCHAR(120),
    concentracao VARCHAR(120),
    via_administracao VARCHAR(100),
    codigo_atc VARCHAR(50),
    registro_anvisa VARCHAR(50),
    fabricante VARCHAR(255),
    controlado BOOLEAN NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE exame_solicitado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    justificativa VARCHAR(1000),
    observacoes VARCHAR(1000),
    data_coleta TIMESTAMP,
    data_resultado TIMESTAMP,
    consulta_id BIGINT NOT NULL,
    exame_base_id BIGINT NOT NULL,
    CONSTRAINT fk_exame_solicitado_consulta
        FOREIGN KEY (consulta_id) REFERENCES consultas (id),
    CONSTRAINT fk_exame_solicitado_exame_base
        FOREIGN KEY (exame_base_id) REFERENCES exame_base (id),
    CONSTRAINT ck_exame_solicitado_status
        CHECK (status IN ('SOLICITADO','AGENDADO','REALIZADO','CANCELADO'))
);

CREATE TABLE medicamento_prescrito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dosagem VARCHAR(120) NOT NULL,
    frequencia VARCHAR(255),
    via VARCHAR(100),
    observacoes VARCHAR(1000),
    data_inicio DATE NOT NULL,
    data_fim DATE,
    ativo BOOLEAN NOT NULL,
    consulta_id BIGINT NOT NULL,
    medicamento_base_id BIGINT,
    CONSTRAINT fk_medicamento_prescrito_consulta
        FOREIGN KEY (consulta_id) REFERENCES consultas (id),
    CONSTRAINT fk_medicamento_prescrito_medicamento_base
        FOREIGN KEY (medicamento_base_id) REFERENCES medicamento_base (id)
);

CREATE TABLE tb_usuario_role (
    usuario_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_usuario_role PRIMARY KEY (usuario_id, role_id),
    CONSTRAINT fk_tb_usuario_role_usuario
        FOREIGN KEY (usuario_id) REFERENCES tb_usuarios (id),
    CONSTRAINT fk_tb_usuario_role_role
        FOREIGN KEY (role_id) REFERENCES tb_role (id)
);

CREATE INDEX idx_consultas_paciente_id ON consultas (paciente_id);
CREATE INDEX idx_consultas_medico_id ON consultas (medico_id);
CREATE INDEX idx_consultas_data_hora ON consultas (data_hora);

CREATE INDEX idx_exame_solicitado_consulta_id ON exame_solicitado (consulta_id);
CREATE INDEX idx_exame_solicitado_exame_base_id ON exame_solicitado (exame_base_id);

CREATE INDEX idx_medicamento_prescrito_consulta_id ON medicamento_prescrito (consulta_id);
CREATE INDEX idx_medicamento_prescrito_medicamento_base_id ON medicamento_prescrito (medicamento_base_id);

CREATE INDEX idx_tb_usuario_role_role_id ON tb_usuario_role (role_id);