BEGIN;

INSERT INTO consultas
(
    data_hora,
    medico_id,
    paciente_id,
    motivo,
    observacoes,
    anamnese,
    diagnostico,
    exame_fisico,
    prescricao,
    status,
    tipo,
    valor_consulta,
    meio_pagamento,
    pago,
    data_pagamento,
    duracao_minutos,
    retorno,
    data_limite_retorno,
    teleconsulta,
    link_acesso,
    plano_saude,
    numero_carteirinha
)
SELECT
    v.data_hora,
    m.usuario_id,
    p.id,
    v.motivo,
    v.observacoes,
    v.anamnese,
    v.diagnostico,
    v.exame_fisico,
    v.prescricao,
    v.status,
    v.tipo,
    v.valor_consulta,
    v.meio_pagamento,
    v.pago,
    v.data_pagamento,
    v.duracao_minutos,
    v.retorno,
    v.data_limite_retorno,
    v.teleconsulta,
    v.link_acesso,
    v.plano_saude,
    v.numero_carteirinha
FROM (
    VALUES
        (
            TIMESTAMP '2025-01-10 09:00:00',
            'drhouse',
            '39053344705',
            'Cefaleia',
            'Paciente refere dor leve',
            'Anamnese A',
            'Sem diagnóstico fechado',
            'Exame normal',
            NULL,
            'AGENDADA',
            'PRESENCIAL',
            250.00,
            'DEBITO',
            FALSE,
            NULL,
            30,
            FALSE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-10 10:00:00',
            'drcameron',
            '29537914806',
            'Alergia',
            'Prurido ocasional',
            'Anamnese B',
            'Rinite alérgica',
            'Exame normal',
            'Loratadina 10mg',
            'CONFIRMADA',
            'PRESENCIAL',
            280.00,
            'CREDITO',
            TRUE,
            TIMESTAMP '2025-01-10 10:05:00',
            30,
            FALSE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-11 09:30:00',
            'drhouse',
            '52998224725',
            'Tontura',
            NULL,
            'Anamnese C',
            'Vertigem posicional',
            'Romberg +',
            NULL,
            'EM_ATENDIMENTO',
            'RETORNO',
            0.00,
            'DEBITO',
            FALSE,
            NULL,
            40,
            TRUE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-11 11:00:00',
            'drcameron',
            '16899535009',
            'Dor abdominal',
            'Jejum 8h',
            'Anamnese D',
            'Suspeita colecistite',
            'Dor à palpação',
            NULL,
            'AGENDADA',
            'URGENCIA',
            350.00,
            'DEBITO',
            FALSE,
            NULL,
            60,
            FALSE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-12 08:00:00',
            'drhouse',
            '35719278060',
            'Acompanhamento',
            NULL,
            'Anamnese E',
            NULL,
            'Exame normal',
            NULL,
            'CONFIRMADA',
            'TELECONSULTA',
            220.00,
            'PIX',
            TRUE,
            TIMESTAMP '2025-01-12 08:01:00',
            30,
            FALSE,
            NULL,
            TRUE,
            'https://teleconsulta.medicflow/consultas/5',
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-12 09:00:00',
            'drcameron',
            '74697131401',
            'Asma',
            'Dispneia noturna',
            'Anamnese F',
            'Asma persistente',
            'Sibilos',
            'Corticoide inalatório',
            'CONCLUIDA',
            'PRESENCIAL',
            260.00,
            'DEBITO',
            TRUE,
            TIMESTAMP '2025-01-12 09:10:00',
            30,
            FALSE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-13 13:00:00',
            'drhouse',
            '86288366006',
            'Enxaqueca',
            NULL,
            'Anamnese G',
            'Migrânea',
            'Exame normal',
            NULL,
            'CANCELADA',
            'RETORNO',
            0.00,
            'DEBITO',
            FALSE,
            NULL,
            30,
            TRUE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-13 14:00:00',
            'drcameron',
            '40672026004',
            'Lombalgia',
            'Dor há 3 semanas',
            'Anamnese H',
            'Lombalgia mecânica',
            'Dor L5',
            'Analgésico',
            'CONCLUIDA',
            'PRESENCIAL',
            270.00,
            'PIX',
            TRUE,
            TIMESTAMP '2025-01-13 14:20:00',
            30,
            FALSE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-14 15:00:00',
            'drhouse',
            '23100257000',
            'Gripe',
            NULL,
            'Anamnese I',
            'Síndrome gripal',
            'Febre 38.2',
            NULL,
            'CONFIRMADA',
            'TELECONSULTA',
            230.00,
            'PIX',
            TRUE,
            TIMESTAMP '2025-01-14 15:02:00',
            20,
            FALSE,
            NULL,
            TRUE,
            'https://teleconsulta.medicflow/consultas/9',
            NULL,
            NULL
        ),
        (
            TIMESTAMP '2025-01-14 16:00:00',
            'drcameron',
            '70548445052',
            'Dismenorreia',
            'Cólica intensa',
            'Anamnese J',
            NULL,
            'Exame normal',
            'Antiespasmódico',
            'AGENDADA',
            'PRESENCIAL',
            250.00,
            'CREDITO',
            FALSE,
            NULL,
            30,
            FALSE,
            NULL,
            FALSE,
            NULL,
            NULL,
            NULL
        )
) AS v(
    data_hora,
    medico_login,
    paciente_cpf,
    motivo,
    observacoes,
    anamnese,
    diagnostico,
    exame_fisico,
    prescricao,
    status,
    tipo,
    valor_consulta,
    meio_pagamento,
    pago,
    data_pagamento,
    duracao_minutos,
    retorno,
    data_limite_retorno,
    teleconsulta,
    link_acesso,
    plano_saude,
    numero_carteirinha
)
JOIN tb_usuarios u
    ON u.login = v.medico_login
JOIN tb_medicos m
    ON m.usuario_id = u.id
JOIN pacientes p
    ON p.cpf = v.paciente_cpf
WHERE NOT EXISTS (
    SELECT 1
    FROM consultas c
    WHERE c.data_hora = v.data_hora
      AND c.medico_id = m.usuario_id
      AND c.paciente_id = p.id
      AND c.motivo = v.motivo
);

COMMIT;