BEGIN;

INSERT INTO medicamento_base (nome_comercial)
SELECT v.nome_comercial
FROM (
    VALUES
        ('Paracetamol 500mg'),
        ('Paracetamol 750mg'),
        ('Paracetamol gotas 200mg/ml'),
        ('Dipirona 500mg'),
        ('Dipirona 1g'),
        ('Dipirona gotas 500mg/ml'),
        ('Ibuprofeno 200mg'),
        ('Ibuprofeno 400mg'),
        ('Ibuprofeno 600mg'),
        ('Naproxeno 250mg'),
        ('Naproxeno 500mg'),
        ('Diclofenaco 50mg'),
        ('Diclofenaco potássico 50mg'),
        ('Cetoprofeno 100mg'),
        ('Meloxicam 15mg'),
        ('Nimesulida 100mg'),
        ('Celecoxibe 200mg'),
        ('Tramadol 50mg'),
        ('Codeína 30mg'),
        ('Morfina 10mg'),
        ('Omeprazol 20mg'),
        ('Pantoprazol 40mg'),
        ('Esomeprazol 40mg'),
        ('Domperidona 10mg'),
        ('Metoclopramida 10mg'),
        ('Ondansetrona 4mg'),
        ('Ondansetrona 8mg'),
        ('Buscopan composto'),
        ('Simeticona 75mg'),
        ('Loperamida 2mg'),
        ('Amoxicilina 500mg'),
        ('Amoxicilina 875mg'),
        ('Amoxicilina+Clavulanato 500/125mg'),
        ('Amoxicilina+Clavulanato 875/125mg'),
        ('Azitromicina 500mg'),
        ('Claritromicina 500mg'),
        ('Cefalexina 500mg'),
        ('Cefuroxima 500mg'),
        ('Ciprofloxacino 500mg'),
        ('Levofloxacino 500mg'),
        ('Sulfametoxazol+Trimetoprima 800/160mg'),
        ('Nitrofurantoína 100mg'),
        ('Fluconazol 150mg'),
        ('Itraconazol 100mg'),
        ('Aciclovir 200mg'),
        ('Valaciclovir 500mg'),
        ('Albendazol 400mg'),
        ('Ivermectina 6mg'),
        ('Loratadina 10mg'),
        ('Cetirizina 10mg'),
        ('Desloratadina 5mg'),
        ('Fexofenadina 120mg'),
        ('Prednisona 5mg'),
        ('Prednisona 20mg'),
        ('Prednisolona 20mg'),
        ('Dexametasona 4mg'),
        ('Betametasona 2mg'),
        ('Salbutamol spray 100mcg'),
        ('Fenoterol gotas'),
        ('Budesonida inalatória 200mcg'),
        ('Beclometasona spray 250mcg'),
        ('Montelucaste 10mg'),
        ('Losartana 50mg'),
        ('Losartana 100mg'),
        ('Valsartana 160mg'),
        ('Amlodipino 5mg'),
        ('Amlodipino 10mg'),
        ('Atenolol 25mg'),
        ('Atenolol 50mg'),
        ('Metoprolol 50mg'),
        ('Propranolol 40mg'),
        ('Hidroclorotiazida 25mg'),
        ('Clortalidona 25mg'),
        ('Furosemida 40mg'),
        ('Espironolactona 25mg'),
        ('Sinvastatina 20mg'),
        ('Sinvastatina 40mg'),
        ('Atorvastatina 20mg'),
        ('Atorvastatina 40mg'),
        ('Rosuvastatina 10mg'),
        ('AAS 100mg'),
        ('Clopidogrel 75mg'),
        ('Rivaroxabana 10mg'),
        ('Rivaroxabana 20mg'),
        ('Apixabana 5mg'),
        ('Metformina 500mg'),
        ('Metformina 850mg'),
        ('Metformina 1000mg'),
        ('Glibenclamida 5mg'),
        ('Gliclazida 30mg'),
        ('Sitagliptina 100mg'),
        ('Insulina NPH'),
        ('Insulina Regular'),
        ('Levotiroxina 25mcg'),
        ('Levotiroxina 50mcg'),
        ('Levotiroxina 75mcg'),
        ('Levotiroxina 100mcg'),
        ('Sertralina 50mg'),
        ('Sertralina 100mg'),
        ('Fluoxetina 20mg'),
        ('Escitalopram 10mg'),
        ('Escitalopram 20mg'),
        ('Clonazepam 0,5mg'),
        ('Clonazepam 2mg'),
        ('Alprazolam 0,5mg'),
        ('Diazepam 10mg'),
        ('Quetiapina 25mg'),
        ('Quetiapina 100mg'),
        ('Zolpidem 10mg'),
        ('Amitriptilina 25mg'),
        ('Nortriptilina 25mg'),
        ('Pregabalina 75mg'),
        ('Gabapentina 300mg'),
        ('Ciclobenzaprina 5mg'),
        ('Ciclobenzaprina 10mg'),
        ('Colírio lubrificante'),
        ('Tobramicina colírio'),
        ('Dorzolamida colírio'),
        ('Cetoconazol creme'),
        ('Miconazol creme'),
        ('Hidrocortisona creme 1%'),
        ('Neomicina+bacitracina pomada'),
        ('Soro fisiológico 0,9% 500ml')
) AS v(nome_comercial)
WHERE NOT EXISTS (
    SELECT 1
    FROM medicamento_base mb
    WHERE mb.nome_comercial = v.nome_comercial
);

COMMIT;