INSERT INTO medicamento_base (
    nome_comercial,
    controlado,
    ativo
)
SELECT
    v.nome_comercial,
    FALSE,
    TRUE
FROM (
    VALUES
        ('Paracetamol'),
        ('Dipirona'),
        ('Ibuprofeno'),
        ('Naproxeno'),
        ('Diclofenaco'),
        ('Cetoprofeno'),
        ('Meloxicam'),
        ('Nimesulida'),
        ('Celecoxibe'),
        ('Tramadol'),
        ('Codeína'),
        ('Morfina'),
        ('Omeprazol'),
        ('Pantoprazol'),
        ('Esomeprazol'),
        ('Domperidona'),
        ('Metoclopramida'),
        ('Ondansetrona'),
        ('Buscopan composto'),
        ('Simeticona'),
        ('Loperamida'),
        ('Amoxicilina'),
        ('Amoxicilina + Clavulanato'),
        ('Azitromicina'),
        ('Claritromicina'),
        ('Cefalexina'),
        ('Cefuroxima'),
        ('Ciprofloxacino'),
        ('Levofloxacino'),
        ('Sulfametoxazol + Trimetoprima'),
        ('Nitrofurantoína'),
        ('Fluconazol'),
        ('Itraconazol'),
        ('Aciclovir'),
        ('Valaciclovir'),
        ('Albendazol'),
        ('Ivermectina'),
        ('Loratadina'),
        ('Cetirizina'),
        ('Desloratadina'),
        ('Fexofenadina'),
        ('Prednisona'),
        ('Prednisolona'),
        ('Dexametasona'),
        ('Betametasona'),
        ('Salbutamol'),
        ('Fenoterol'),
        ('Budesonida'),
        ('Beclometasona'),
        ('Montelucaste'),
        ('Losartana'),
        ('Valsartana'),
        ('Amlodipino'),
        ('Atenolol'),
        ('Metoprolol'),
        ('Propranolol'),
        ('Hidroclorotiazida'),
        ('Clortalidona'),
        ('Furosemida'),
        ('Espironolactona'),
        ('Sinvastatina'),
        ('Atorvastatina'),
        ('Rosuvastatina'),
        ('AAS'),
        ('Clopidogrel'),
        ('Rivaroxabana'),
        ('Apixabana'),
        ('Metformina'),
        ('Glibenclamida'),
        ('Gliclazida'),
        ('Sitagliptina'),
        ('Insulina NPH'),
        ('Insulina Regular'),
        ('Levotiroxina'),
        ('Sertralina'),
        ('Fluoxetina'),
        ('Escitalopram'),
        ('Clonazepam'),
        ('Alprazolam'),
        ('Diazepam'),
        ('Quetiapina'),
        ('Zolpidem'),
        ('Amitriptilina'),
        ('Nortriptilina'),
        ('Pregabalina'),
        ('Gabapentina'),
        ('Ciclobenzaprina'),
        ('Colírio lubrificante'),
        ('Tobramicina colírio'),
        ('Dorzolamida colírio'),
        ('Cetoconazol creme'),
        ('Miconazol creme'),
        ('Hidrocortisona creme'),
        ('Neomicina + Bacitracina pomada'),
        ('Soro fisiológico 0,9%')
) AS v(nome_comercial)
WHERE NOT EXISTS (
    SELECT 1
    FROM medicamento_base mb
    WHERE mb.nome_comercial = v.nome_comercial
);