spring.application.name=MedicFlow

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.time-zone=UTC

logging.pattern.level=%5p [traceId:%X{traceId:-N/A}]

# Safe default profile
spring.profiles.default=prod

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

spring.sql.init.mode=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.h2.console.enabled=false