server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/medicflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoint.health.show-details=always

spring.devtools.add-properties=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

